import uuid
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils import timezone

from .storage import private_attachment_storage
from . import uploads


class Message(models.Model):
    ROLES = [('admin', 'Admin'), ('agent', 'Agent')]
    sender_id = models.IntegerField()
    sender_role = models.CharField(max_length=10, choices=ROLES)
    receiver_id = models.IntegerField()
    receiver_role = models.CharField(max_length=10, choices=ROLES)
    # blank=True because a message can be attachments only, with no caption
    content = models.TextField(blank=True)
    read = models.BooleanField(default=False)
    # Delivery receipts: `delivered` flips when the recipient's browser fetches the
    # message, `read` when they open the conversation. Drives the ✓ / ✓✓ / blue ✓✓ ticks.
    delivered = models.BooleanField(default=False)
    delivered_at = models.DateTimeField(null=True, blank=True)
    read_at = models.DateTimeField(null=True, blank=True)
    # A broadcast is one row (receiver_id=0) shown in the shared Team channel.
    is_broadcast = models.BooleanField(default=False)
    reply_to = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, related_name='replies')
    # Legacy single attachment (pre-Attachment model). Kept so old conversations still open;
    # new uploads always go through the Attachment model below.
    attachment = models.FileField(upload_to='chat_attachments/%Y/%m/', blank=True, null=True)
    # Idempotency key generated by the browser so a retried send never creates a duplicate.
    client_id = models.CharField(max_length=64, blank=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f"[{self.sender_role}→{self.receiver_role}] {self.content[:40] or '[attachment]'}"

    IMAGE_EXTS = ('.jpg', '.jpeg', '.png', '.gif', '.webp')

    @property
    def attachment_is_image(self):
        if not self.attachment:
            return False
        return self.attachment.name.lower().endswith(self.IMAGE_EXTS)

    @property
    def status(self):
        if self.read: return 'read'
        if self.delivered: return 'delivered'
        return 'sent'


def attachment_path(instance, filename):
    """Unguessable storage name; the extension is kept, the original name lives in the DB."""
    ext = uploads.get_ext(filename)
    return f"chat/{timezone.now():%Y/%m}/{uuid.uuid4().hex}{'.' + ext if ext else ''}"


class Attachment(models.Model):
    """One uploaded file. Uploaded first (message=None), then bound to a message on send."""
    message = models.ForeignKey(Message, null=True, blank=True, on_delete=models.CASCADE, related_name='attachments')
    file = models.FileField(upload_to=attachment_path, storage=private_attachment_storage, max_length=255)
    original_filename = models.CharField(max_length=255)
    file_extension = models.CharField(max_length=16, blank=True)
    mime_type = models.CharField(max_length=120)
    file_size = models.BigIntegerField()
    uploaded_by_id = models.IntegerField()
    uploaded_by_role = models.CharField(max_length=10, choices=Message.ROLES)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['uploaded_at', 'id']

    def __str__(self):
        return self.original_filename

    @property
    def storage_filename(self):
        return self.file.name.rsplit('/', 1)[-1]

    @property
    def kind(self): return uploads.file_kind(self.file_extension)
    @property
    def category(self): return uploads.file_category(self.file_extension)
    @property
    def preview(self): return uploads.preview_type(self.file_extension)


@receiver(post_delete, sender=Attachment)
def _delete_attachment_file(sender, instance, **kwargs):
    try:
        if instance.file:
            instance.file.delete(save=False)
    except Exception:
        pass
