services:
  - type: web
    name: muddo-agro-api
    runtime: python
    rootDir: backend
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py check --fail-level ERROR &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      python manage.py seed_data
    startCommand: gunicorn muddo_project.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "muddo-agro-api.onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: WHATSAPP_NUMBER
        value: "256772507582"
      - key: GOOGLE_MAPS_KEY
        sync: false
      - key: GA_MEASUREMENT_ID
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_REGION_NAME
        sync: false
      - key: AWS_S3_ENDPOINT_URL
        sync: false
      - key: AWS_S3_CUSTOM_DOMAIN
        sync: false
    plan: free
