from django.urls import path
from apps.analytics import views
urlpatterns = [
    path('', views.admin_dashboard, name='admin_dashboard'),
    path('products/', views.admin_products, name='admin_products'),
    path('products/add/', views.admin_add_product, name='admin_add_product'),
    path('products/<int:pid>/edit/', views.admin_edit_product, name='admin_edit_product'),
    path('products/<int:pid>/delete/', views.admin_delete_product, name='admin_delete_product'),
    path('products/<int:pid>/photos/add/', views.admin_add_product_photo, name='admin_add_product_photo'),
    path('products/photos/<int:iid>/delete/', views.admin_delete_product_photo, name='admin_delete_product_photo'),
    path('reviews/', views.admin_reviews, name='admin_reviews'),
    path('reviews/<int:rid>/<str:action>/', views.admin_review_action, name='admin_review_action'),
    path('requests/', views.admin_requests, name='admin_requests'),
    path('requests/<int:rid>/update/', views.admin_update_request, name='admin_update_request'),
    path('distributors/', views.admin_distributors, name='admin_distributors'),
    path('distributors/add/', views.admin_add_distributor, name='admin_add_distributor'),
    path('distributors/<int:did>/edit/', views.admin_edit_distributor, name='admin_edit_distributor'),
    path('distributors/<int:did>/delete/', views.admin_delete_distributor, name='admin_delete_distributor'),
    path('inventory/', views.admin_inventory, name='admin_inventory'),
    path('inventory/update/', views.admin_update_inventory, name='admin_update_inventory'),
    path('newsletter/', views.admin_newsletter, name='admin_newsletter'),
    path('import/', views.admin_import, name='admin_import'),
    path('settings/', views.admin_settings, name='admin_settings'),
    path('profile/', views.admin_profile, name='admin_profile'),
    path('site-content/', views.admin_site_content, name='admin_site_content'),
    path('site-content/update/', views.admin_update_site_settings, name='admin_update_site_settings'),
    path('site-content/faqs/add/', views.admin_add_faq, name='admin_add_faq'),
    path('site-content/faqs/<int:fid>/edit/', views.admin_edit_faq, name='admin_edit_faq'),
    path('site-content/faqs/<int:fid>/delete/', views.admin_delete_faq, name='admin_delete_faq'),
    path('leadership/', views.admin_leadership, name='admin_leadership'),
    path('leadership/add/', views.admin_add_leader, name='admin_add_leader'),
    path('leadership/<int:lid>/edit/', views.admin_edit_leader, name='admin_edit_leader'),
    path('leadership/<int:lid>/delete/', views.admin_delete_leader, name='admin_delete_leader'),
    path('api/analytics/', views.api_analytics, name='api_analytics'),
]
